### ISSUE TITLE
Basic/self explanatory programs to-do list

### ISSUE THREAD

**Issue by IoIxD** [IoIxD/TerminalWars#21]
- [ ] Scientific Calculator app
     - [ ] A graphing calculator app that only lets you graph very basic functions. This might not even be necessary.
- [ ] Image viewer
- [ ] Notepad
    - [ ] The UI should be a literally sticky note to contextualize this within TerminalWars
- [ ] Paint program
    - [ ] Probably has the ability to show others the image you are working on in real time.
- [ ] [neofetch](https://github.com/dylanaraps/neofetch/)
- [ ] 3D Space Cadet Pinball parody? maybe?
- [ ] Solitare
- [ ] TIC-80 player (see: #13)
